import LogoIcon from "./LogoIcon.vue";
import TelegramIcon from "./TelegramIcon.vue";
import WhatsappIcon from "./WhatsappIcon.vue";
import ArrowLeftIcon from "./ArrowLeftIcon.vue";
import ArrowRightIcon from "./ArrowRightIcon.vue";
import BigArrowIcon from "./BigArrowIcon.vue";
import PlusIcon from "./PlusIcon.vue";
import ParadigmaIcon from "./ParadigmaIcon.vue";
import CloseIcon from "./CloseIcon.vue";

export { LogoIcon };
export { TelegramIcon };
export { WhatsappIcon };
export { ArrowLeftIcon };
export { ArrowRightIcon };
export { BigArrowIcon };
export { PlusIcon };
export { ParadigmaIcon };
export { CloseIcon };
